select * from customer limit 20
-- 1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,
       purchase_amount FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

  -- Q3. What are the top 5 products based on their average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. What is the average purchase amount for each shipping type?

SELECT shipping_type,
       ROUND(AVG(purchase_amount)::numeric, 2) AS average_purchase_amount
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       ROUND(AVG(purchase_amount)::numeric, 2) AS average_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(
           (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
           / COUNT(*))::numeric,
           2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)

SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(
        (COUNT(*) * 100.0 / SUM(COUNT(*)) OVER ())::numeric,
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY percentage DESC;

-- Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;