select * from customer limit 20
-- 1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,
       purchase_amount FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

  -- Q3. What are the top 5 products based on their average review rating?

SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;